favicon: favicon/favicon.svg

footer: |
  <p> Powered by
    <a class="footer-link" href="https://github.com/cwxyz007/hexo-simple-template" target="_blank" rel="noopener">Simple</a>
    and
    <a class="footer-link" href="https://hexo.io" target="_blank" rel="noopener">Hexo</a>
    , Made By
    <a class="footer-link" href="https://github.com/cwxyz007" target="_blank" rel="noopener">@Fantasy</a>
  </p>

# Size: 100x100
avatar: imgs/avatar.png

# Icon use fontawesome class
menu:
  Home:
    path: /
    icon: home

# Icon use fontawesome class
links:
   Github:
     link: https://github.com/karin722
     icon: github
#   Email:
#     link: mailto:x.li.gem@gmail.com
#     icon: envelope

# Service worker
sw: true

# Creative commons license
cclicense:
  text: 版权声明：本文使用 @license 协议
  # All in lower case
  cc by-nc 4.0: https://creativecommons.org/licenses/by-nc/4.0/deed.zh

# Google analytics
ga:
  active: false
  id: ""

# Baidu analytics
ba:
  active: false
  # Example for get id:
  # ```js
  # hm.src = "https://hm.baidu.com/hm.js?044e5dc9f3bc0a3b3042d15a4bbd8cae";
  # ```
  # The id is 044e5dc9f3bc0a3b3042d15a4bbd8cae
  id: ""
